config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "localhost:3000"

  resources :versions
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :users
  resources :apps
  resources :apps do
    resources :versions
  end
  resources :apps do
    resources :users
  end
  root 'apps#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/version.rb
class Version < ApplicationRecord

  has_one_attached :image
  has_many_attached :screenshots
  belongs_to :app
  has_one_attached :apk
  

  def apk_on_disk
  	ActiveStorage::Blob.service.send(:path_for, apk.key)
  end

  def to_s
  	self.app.name
  	self.apk
  end

  validates :apk, presence: true
  validates :image, presence: true, blob: { content_type: :image }
  validates :screenshots, presence: true, blob: { content_type: :image }

end

app/controllers/versions_controller.rb
class VersionsController < ApplicationController
  before_action :authenticate_admin_user!
  before_action :set_version, only: [:show, :edit, :update, :destroy]

  # GET /versions
  # GET /versions.json
  def index
    @versions = Version.all
  end

  # GET /versions/1
  # GET /versions/1.json
  def show
  end

  # GET /versions/new
  def new
    @version = Version.new
  end

  # GET /versions/1/edit
  def edit
  end

  # POST /versions
  # POST /versions.json
  def create
    @version = Version.new(version_params)
    @version.image.attach(params[:version][:image]) 
    @version.screenshots.attach(params[:version][:screenshots])

    respond_to do |format|
      if @version.save
        format.html { redirect_to @version, notice: 'Version was successfully created.' }
        format.json { render :show, status: :created, location: @version }
      else
        format.html { render :new }
        format.json { render json: @version.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /versions/1
  # PATCH/PUT /versions/1.json
  def update
    respond_to do |format|
      if @version.update(version_params)
        format.html { redirect_to @version, notice: 'Version was successfully updated.' }
        format.json { render :show, status: :ok, location: @version }
      else
        format.html { render :edit }
        format.json { render json: @version.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /versions/1
  # DELETE /versions/1.json
  def destroy
    @version.destroy
    respond_to do |format|
      format.html { redirect_to versions_url, notice: 'Version was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_version
      @version = Version.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def version_params
      params.require(:version).permit(:name, :code, :description, :apk, :image, :app_id, screenshots: [])
    end
end

app/helpers/version_helper.rb
module VersionHelper
end

app/helpers/versions_helper.rb
module VersionsHelper
end

app/views/versions/_form.html.erb
<%= form_with(model: version, local: true) do |form| %>
  <% if version.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(version.errors.count, "error") %> prohibited this version from being saved:</h2>

      <ul>
      <% version.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/versions/edit.html.erb
<h1>Editing Version</h1>

<%= render 'form', version: @version %>

<%= link_to 'Show', @version %> |
<%= link_to 'Back', versions_path %>

app/views/versions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Versions</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Description</th>
      <th>Code</th>
      <th>App</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @versions.each do |version| %>
      <tr>
        <td><%= version.id %></td>
        <td><%= version.name %></td>
        <td><%= version.description %></td>
        <td><%= version.code %></td>
        <td><%= version.app.name %></td>
        <td><%= link_to 'Show', version %></td>
        <td><%= link_to 'Edit', edit_version_path(version) %></td>
        <td><%= link_to 'Destroy', version, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Version', new_version_path %>

app/views/versions/new.html.erb
<h1>New Version</h1>

<%= render 'form', version: @version %>

<%= link_to 'Back', versions_path %>

app/views/versions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Logo</strong>
  <%= image_tag @version.image, disposition: "attachment" %>
</p>

<p>
  <strong>screenshots</strong>
  <% @version.screenshots.each do |ss| %>
  <%= image_tag ss, disposition: "attachment", class: "screenshots", "data-enlargable" => true %>
  <% end %>
</p>

<p>
  url = 
  <img src="#{url}" alt="">
</p>

<p>
	<strong>Versin ID</strong>
	<%= @version.id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @version.name %>
</p>

<p>
  <strong>Code:</strong>
  <%= @version.code %>
</p>

<p>
  <strong>File</strong>
  <%= @version.apk.attached? %>
</p>

<p>
  <strong>App:</strong>
  <%= @version.app.name %>
</p>




<%= link_to 'Edit', edit_version_path(@version) %> |
<%= link_to 'Back', versions_path %>