config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "localhost:3000"

  resources :versions
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :users
  resources :apps
  resources :apps do
    resources :versions
  end
  resources :apps do
    resources :users
  end
  root 'apps#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/apps/_form.html.erb
<%= form_for @app do |form| %>
  <% if app.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(app.errors.count, "error") %> prohibited this app from being saved:</h2>

      <ul>
      <% app.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :shortescription %>
    <%= form.text_field :shortdescription %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :is_public %>
    <%= form.check_box :is_public %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/apps/edit.html.erb
<h1>Editing App</h1>

<%= render 'form', app: @app %>

<%= link_to 'Show', @app %> |
<%= link_to 'Back', apps_path %>
	

app/views/apps/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Document</title>
</head>
<body>

<div class="header">
   Apps <br> <br>
   Download latest versions of mobile apps from Zwenexsys.
</div>
<br>

<div class="app-index-card">
<div class="card apps">
  
  <% if user_signed_in? %>
  <p class="app-status">My Apps</p>
  <div class="row">
    <% current_user.apps.each do |app| %>
    <div class="col-md-3">
      <div  class="card showcase">
        <%= link_to app, class: "link-app" do %>
        <div class="card-img-top"><%= image_tag (app.versions.last.image),class: "app-logo" if app.versions.last.image.attached? %></div>        
        <div class="card-body">
          <p class="card-title">
          <span class="app-name"><%= app.name %></span>
          </p>
          <p class="card-text app-sd">
            <%= app.shortdescription %>
          </p>
        </div>
        <% end %>
      </div>
    </div>
  <% end %>
  </div>

<hr width="100%" style="border-top: 1px solid #F4CC70">

    <div><p class="app-status">Public Apps</div>

<div class="row"> 
  <% @public_apps = @apps - current_user.apps %>
  <% @public_apps.each do |app| %>
    <div class="col-md-3">
      <div  class="card showcase">
        <%= link_to app, class: "link-app" do %>
        <div class="card-img-top"><%= image_tag (app.versions.last.image), class: "app-logo" if app.versions.last.image.attached? %></div>        
        <div class="card-body">
          <p class="card-title">
            <span class="app-name"><%= app.name %></span>
          </p>
        <p class="card-text app-sd">
          <%= app.shortdescription %>
        </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

  <% else %>

    <div class="row">
    <% @apps.each do |app| %>
    <div class="col-md-3">
      <div  class="card showcase">
        <%= link_to app, class: "link-app" do %>
        <div class="card-img-top"><%= image_tag (app.versions.last.image), class: "app-logo" if app.versions.last.image.attached? %></div>        
        <div class="card-body">
          <p class="card-title">
          <span class="app-name"><%= app.name %></span>
          </p>
          <p class="card-text app-sd">
          <%= app.shortdescription %>
          </p>    
        </div>
        <% end %>
      </div>
    </div>
  <% end %>
  </div>

<% end %>

</div>
</div>
<br>



</body>
</html>

app/views/apps/new.html.erb
<h1>New App</h1>

<%= render 'form', app: @app %>

<%= link_to 'Back', apps_path %>

app/views/apps/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
</head>
<body>
	<br>
<div class="card app-show-card">

<div class="card-img-top show-card">
	<%= image_tag(@app.versions.last.image, class: 'logo')  if @app.versions.last.image.present? %> <br>
	<p style="font-family: Raleway; font-size: 18px; font-weight: 550"><%= @app.name %></p>
	<div>
		<%= link_to 'Download', rails_blob_path(@app.versions.last.apk, disposition: :attachment), class: "link btn btn-primary" if @app.versions.last.apk.attached? %>
	</div>	
</div>

<div class="card-body">
		<div class="row slider">
			<div>
				<% @app.versions.last.screenshots.each do |ss| %>
				<%= image_tag(ss, class: 'screenshots',"data-enlargable" => "true") %>  
	     		<% end %>
			</div>
		</div>
			
	<p class="card-description">
	 	<details style="font-size: 14px;">
        <summary><span style="font-size: 15px;"><%= @app.description[0, 90] %></span></summary>
        <p style="font-size: 14px;">
            <%= @app.description[30, @app.description.length - 1] %>
        </p>
        </details>
	</p>
	<br>

	<strong style="font-size: 16px;">What is new</strong>

	<p class="card-version-description">
		<p style="font-size: 14px;"><%= "- " + @app.versions.last.description if @app.versions.present? %> </p> 
	</p>

	<hr width="100%" style="border-top: 1px solid grey;">

	<strong style="font-size: 16px;">Additional information</strong>

	<p class="card-created-at">
		<p style="font-size: 14px;">Released on <span style="text-align: right;"><%= @app.versions.first.created_at.to_date if @app.versions.present? %></span></p>
	</p>

	<p class="card-version">
		<p style="font-size: 14px;">Version - <%= @app.versions.last.code if @app.versions.present? %></p>
	</p>

	<p class="card-updated-at">
		<p style="font-size: 14px;">Updated <%= distance_of_time_in_words_to_now(@app.versions.last.updated_at.strftime("%FT%T")) + " ago" if @app.versions.present? %></p>
	</p>

	<p class="card-andriod-version">
		<p style="font-size: 14px;">Minimal andriod version - <%= @app.versions.last.AndriodVersion %></p>
	</p>

		<hr width="100%" style="border-top: 1px solid grey;">	

	<div class="previous-versions-web">
		<strong style="font-size: 16px;">Download previous versions</strong>
		<table class="table">
			<% if @app.versions.count > 1 %>
			<% (0...@app.versions.count-1).each do |previous_versions| %>
			<tbody>
				<tr>
					<td><%= @app.versions[previous_versions].name %>
					</td>
					<td><%= @app.versions[previous_versions].description %></td>
					<td><%= @app.versions[previous_versions].created_at.to_date %></td>
					<td><%= link_to 'Download', rails_blob_path(@app.versions[previous_versions].apk, disposition: :attachment), class: "link btn btn-primary" if @app.versions[previous_versions].apk.attached? %></td>
				</tr>
			</tbody>
			<% end %>
			<% else %>
				<p style="font-size: 14px;">There is no previous versions yet.</p>
			<% end %> 
		</table>
	</div>


	<div class="previous-versions-mobile" style="text-align: center;">
		<div style="text-align: left;">
			<strong style="font-size: 16px;">Download previous versions</strong>
		</div>
		<% if @app.versions.count > 1 %>
			<% (0...@app.versions.count-1).each do |previous_versions| %> 
			<%= @app.versions[previous_versions].name %> <br>
			<%= @app.versions[previous_versions].description %> <br>
			<%= @app.versions[previous_versions].created_at.to_date %> <br>
			<%= link_to 'Download', rails_blob_path(@app.versions[previous_versions].apk, disposition: :attachment), class: "link btn btn-primary" if @app.versions[previous_versions].apk.attached? %>
			<hr width="100%" style="border-top: 1px solid grey;">
			<% end %>
		<% else %>
			<p style="font-size: 14px;">There is no previous versions yet.</p>
		<% end %> 
	</div>

</div>

</div>

<br>

</body>
</html>